/*
 * Created on 19 oct. 2018 ( Time 11:15:48 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.smile.colloque.helper.dto;

import java.util.List;

import ci.smile.colloque.helper.contract.SearchParam;
import ci.smile.colloque.helper.extra.classes.CountParticipantByColloque;
import ci.smile.colloque.helper.extra.classes.ParticipantExtra;

/**
 * Persistent class for entity stored in table "colloque"
 *
 * @author Telosys Tools Generator
 *
 */


public class ColloqueDto implements Cloneable {


    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
	/*
	 * 
	 */
   
    private Integer    id           ;
    private String     nom          ;
    private String       date         ;
    private Integer universiteId  ;
    
    
    //-------------------------------------------------------------
    // SPECIFIC SERVICE COUNT Colloque Partcipant
    //-------------------------------------------------------------    
    private CountParticipantByColloque countParticipantByColloque;
    
    //-------------------------------------------------------------
    // SPECIFIC SERVICE FOR Colloque DETAILS
    //-------------------------------------------------------------    

    private CountParticipantByColloque  NbreColloqueParticipant;
    private List<ParticipantExtra>  conferencierList;
    private List<ParticipantExtra>  organisateurList;
    
    
    
    
    
    private SearchParam<Integer>    idParam           ;
    private SearchParam<String>     nomParam          ;
    private SearchParam<String>       dateParam       ;
    private SearchParam<Integer> universiteIdParam    ;
    
    

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public Integer getId() {
    return this.id;
    
    }
    
    public void setId( Integer id ) {
    	this.id=id;
    }
    
    public String getNom() {
    	return this.nom;
    }
    
    public void setNom(String nom) {
    	this.nom=nom;
    }
    
    public String getDate() {
    	return this.date;
    }
    
    public void setDate(String date) {
    	this.date=date;
    }
    
    public Integer getUniversiteId() {
    	return this.universiteId;
    }
    
    public void setUniversiteId(Integer universiteId) {
    	this.universiteId= universiteId;
    	
    }
	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}

	public SearchParam<Integer> getIdParam() {
		return idParam;
	}

	public void setIdParam(SearchParam<Integer> idParam) {
		this.idParam = idParam;
	}

	public SearchParam<String> getNomParam() {
		return nomParam;
	}

	public void setNomParam(SearchParam<String> nomParam) {
		this.nomParam = nomParam;
	}

	public SearchParam<String> getDateParam() {
		return dateParam;
	}

	public void setDateParam(SearchParam<String> dateParam) {
		this.dateParam = dateParam;
	}

	public SearchParam<Integer> getUniversiteIdParam() {
		return universiteIdParam;
	}

	public void setUniversiteIdParam(SearchParam<Integer> universiteIdParam) {
		this.universiteIdParam = universiteIdParam;
	}

	public CountParticipantByColloque getCountParticipantByColloque() {
		return countParticipantByColloque;
	}

	public void setCountParticipantByColloque(CountParticipantByColloque countParticipantByColloque) {
		this.countParticipantByColloque = countParticipantByColloque;
	}

	
	
	
	
	
	


	public List<ParticipantExtra> getConferencierList() {
		return conferencierList;
	}

	public void setConferencierList(List<ParticipantExtra> conferencierList) {
		this.conferencierList = conferencierList;
	}

	public List<ParticipantExtra> getOrganisateurList() {
		return organisateurList;
	}

	public void setOrganisateurList(List<ParticipantExtra> organisateurList) {
		this.organisateurList = organisateurList;
	}

	
	
	public CountParticipantByColloque getNbreColloqueParticipant() {
		return NbreColloqueParticipant;
	}

	public void setNbreColloqueParticipant(CountParticipantByColloque nbreColloqueParticipant) {
		NbreColloqueParticipant = nbreColloqueParticipant;
	}


}
