/*
 * Created on 18 oct. 2018 ( Time 18:53:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.smile.colloque.helper.dto;

import ci.smile.colloque.helper.contract.SearchParam;

/**
 * Persistent class for entity stored in table "exposer"
 *
 * @author Telosys Tools Generator
 *
 */


public class ExposerDto implements  Cloneable {


    private Integer    id           ;
    private String     titre        ;
    private String     resumer      ;
    
    
    private SearchParam<Integer> idParam ;
    private SearchParam<String>  titreParam        ;
    private SearchParam<String>  resumerParam      ;  
    
    
    
    
    

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setTitre( String titre ) {
        this.titre = titre;
    }
    public String getTitre() {
        return this.titre;
    }


    public void setResumer( String resumer ) {
        this.resumer = resumer;
    }
    public String getResumer() {
        return this.resumer;
    }

    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD// The Params
    //----------------------------------------------------------------------
    
    public void setIdParam( SearchParam<Integer> idParam ) {
        this.idParam = idParam ;
    }
    public SearchParam<Integer> getIdParam() {
        return this.idParam;
    }
    public void setTitreParam( SearchParam<String> titreParam ) {
        this.titreParam = titreParam;
    }
    public SearchParam<String> getTitreParam() {
        return this.titreParam;
    }


    public void setResumerParam( SearchParam<String> resumerParam ) {
        this.resumerParam = resumerParam;
    }
    public SearchParam<String> getResumerParam() {
        return this.resumerParam;
    }

	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
