/*
 * Created on 18 oct. 2018 ( Time 18:53:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.smile.colloque.helper.dto;

import ci.smile.colloque.helper.contract.SearchParam;

/**
 * Persistent class for entity stored in table "inscription"
 *
 * @author Telosys Tools Generator
 *
 */


public class InscriptionDto implements  Cloneable {


    private Integer    id           ;
    private String       date         ;
    private String     numeroInscription ;
    private Boolean    presence     ;
    private Integer participantId ;
    private Integer colloqueId    ;
    
    
    
    
    private ParticipantDto participantDto ;
    private String colloqueName;
//    private ColloqueDto colloqueDto;
    
    
    
    
    private SearchParam<Integer>    idParam           ;
    private SearchParam<String>       dateParam         ;
    private SearchParam<String>     numeroInscriptionParam ;
    private SearchParam<Boolean>    presenceParam     ;
    private SearchParam<Integer> participantIdParam ;
    private SearchParam<Integer> colloqueIdParam    ;

 
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }


    public void setDate( String date ) {
        this.date = date;
    }
    public String getDate() {
        return this.date;
    }

    public void setNumeroInscription( String numeroInscription ) {
        this.numeroInscription = numeroInscription;
    }
    public String getNumeroInscription() {
        return this.numeroInscription;
    }

 
    public void setPresence( Boolean presence ) {
        this.presence = presence;
    }
    public Boolean getPresence() {
        return this.presence;
    }



    public void setParticipantId( Integer participantId ) {
        this.participantId = participantId;
    }
    public Integer getParticipantId() {
        return this.participantId;
    }


    public void setColloqueId( Integer colloqueId ) {
        this.colloqueId = colloqueId;
    }
    public Integer getColloqueId() {
        return this.colloqueId;
    }




	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
	public SearchParam<Integer> getIdParam() {
		return idParam;
	}
	public void setIdParam(SearchParam<Integer> idParam) {
		this.idParam = idParam;
	}
	public SearchParam<String> getDateParam() {
		return dateParam;
	}
	public void setDateParam(SearchParam<String> dateParam) {
		this.dateParam = dateParam;
	}
	public SearchParam<String> getNumeroInscriptionParam() {
		return numeroInscriptionParam;
	}
	public void setNumeroInscriptionParam(SearchParam<String> numeroInscriptionParam) {
		this.numeroInscriptionParam = numeroInscriptionParam;
	}
	public SearchParam<Boolean> getPresenceParam() {
		return presenceParam;
	}
	public void setPresenceParam(SearchParam<Boolean> presenceParam) {
		this.presenceParam = presenceParam;
	}
	public SearchParam<Integer> getParticipantIdParam() {
		return participantIdParam;
	}
	public void setParticipantIdParam(SearchParam<Integer> participantIdParam) {
		this.participantIdParam = participantIdParam;
	}
	public SearchParam<Integer> getColloqueIdParam() {
		return colloqueIdParam;
	}
	public void setColloqueIdParam(SearchParam<Integer> colloqueIdParam) {
		this.colloqueIdParam = colloqueIdParam;
	}
	
	
	
	
	
	
	
	public ParticipantDto getParticipantDto() {
		return participantDto;
	}
	public void setParticipantDto(ParticipantDto participantDto) {
		this.participantDto = participantDto;
	}
//	public ColloqueDto getColloqueDto() {
//		return colloqueDto;
//	}
//	public void setColloqueDto(ColloqueDto colloqueDto) {
//		this.colloqueDto = colloqueDto;
//	}
	public String getColloqueName() {
		return colloqueName;
	}
	public void setColloqueName(String colloqueName) {
		this.colloqueName = colloqueName;
	}

}
