/*
 * Created on 18 oct. 2018 ( Time 18:53:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.smile.colloque.helper.dto;

import ci.smile.colloque.helper.contract.SearchParam;

/**
 * Persistent class for entity stored in table "organisateur"
 *
 * @author Telosys Tools Generator
 *
 */

public class OrganisateurDto implements Cloneable {

    private Integer    id           ;
    private String     numeroDeTelephone ;
    private Integer participantId ;
    private Integer colloqueId    ;
    
    
    private InscriptionDto inscriptionDto ;
    
    
    
    
    private SearchParam<Integer>    idParam           ;
    private SearchParam<String>     numeroDeTelephoneParam ;
    private SearchParam<Integer> participantIdParam ;
    private SearchParam<Integer> colloqueIdParam    ;
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }


    public void setNumeroDeTelephone( String numeroDeTelephone ) {
        this.numeroDeTelephone = numeroDeTelephone;
    }
    public String getNumeroDeTelephone() {
        return this.numeroDeTelephone;
    }


    public void setParticipantId( Integer participantId ) {
        this.participantId = participantId;
    }
    public Integer getParticipantId() {
        return this.participantId;
    }


    public void setColloqueId( Integer colloqueId ) {
        this.colloqueId = colloqueId;
    }
    public Integer getColloqueId() {
        return this.colloqueId;
    }



	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
	public SearchParam<Integer> getIdParam() {
		return idParam;
	}
	public void setIdParam(SearchParam<Integer> idParam) {
		this.idParam = idParam;
	}
	public SearchParam<String> getNumeroDeTelephoneParam() {
		return numeroDeTelephoneParam;
	}
	public void setNumeroDeTelephoneParam(SearchParam<String> numeroDeTelephoneParam) {
		this.numeroDeTelephoneParam = numeroDeTelephoneParam;
	}
	public SearchParam<Integer> getParticipantIdParam() {
		return participantIdParam;
	}
	public void setParticipantIdParam(SearchParam<Integer> participantIdParam) {
		this.participantIdParam = participantIdParam;
	}
	public SearchParam<Integer> getColloqueIdParam() {
		return colloqueIdParam;
	}
	public void setColloqueIdParam(SearchParam<Integer> colloqueIdParam) {
		this.colloqueIdParam = colloqueIdParam;
	}
	
	
	public InscriptionDto getInscriptionDto() {
		return inscriptionDto;
	}
	public void setInscriptionDto(InscriptionDto inscriptionDto) {
		this.inscriptionDto = inscriptionDto;
	}
}
