/*
 * Created on 18 oct. 2018 ( Time 18:53:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.smile.colloque.helper.dto;

import ci.smile.colloque.helper.contract.SearchParam;

/**
 * Persistent class for entity stored in table "presentation"
 *
 * @author Telosys Tools Generator
 *
 */


public class PresentationDto implements Cloneable {

    private Integer    id           ;
    private String     resumer      ;
    private Integer colloqueId    ;
    private Integer conferencierId;
    private Integer exposerId     ;
    
    
    
    private SearchParam<Integer>    idParam           ;
    private SearchParam<String>     resumerParam      ;
    private SearchParam<Integer> colloqueIdParam    ;
    private SearchParam<Integer> conferencierIdParam;
    private SearchParam<Integer> exposerIdParam     ;

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

 
    public void setResumer( String resumer ) {
        this.resumer = resumer;
    }
    public String getResumer() {
        return this.resumer;
    }


    public void setColloqueId( Integer colloqueId ) {
        this.colloqueId = colloqueId;
    }
    public Integer getColloqueId() {
        return this.colloqueId;
    }


    public void setConferencierId( Integer conferencierId ) {
        this.conferencierId = conferencierId;
    }
    public Integer getConferencierId() {
        return this.conferencierId;
    }


    public void setExposerId( Integer exposerId ) {
        this.exposerId = exposerId;
    }
    public Integer getExposerId() {
        return this.exposerId;
    }


	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
	public SearchParam<Integer> getIdParam() {
		return idParam;
	}
	public void setIdParam(SearchParam<Integer> idParam) {
		this.idParam = idParam;
	}
	public SearchParam<String> getResumerParam() {
		return resumerParam;
	}
	public void setResumerParam(SearchParam<String> resumerParam) {
		this.resumerParam = resumerParam;
	}
	public SearchParam<Integer> getColloqueIdParam() {
		return colloqueIdParam;
	}
	public void setColloqueIdParam(SearchParam<Integer> colloqueIdParam) {
		this.colloqueIdParam = colloqueIdParam;
	}
	public SearchParam<Integer> getConferencierIdParam() {
		return conferencierIdParam;
	}
	public void setConferencierIdParam(SearchParam<Integer> conferencierIdParam) {
		this.conferencierIdParam = conferencierIdParam;
	}
	public SearchParam<Integer> getExposerIdParam() {
		return exposerIdParam;
	}
	public void setExposerIdParam(SearchParam<Integer> exposerIdParam) {
		this.exposerIdParam = exposerIdParam;
	}
}
