/*
 * Created on 29 oct. 2018 ( Time 11:41:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.smile.colloque.dao.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "conferencier"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="conferencier" )
public class Conferencier implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
	/*
	 * 
	 */
    @Id
    @Column(name="participant_id", nullable=false)
    private Integer    participantId ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	/*
	 * 
	 */
    @Column(name="organisateur")
    private Boolean    organisateur ;

	// "institutionId" (column "institution_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="participant_id", referencedColumnName="id", insertable=false, updatable=false)
    private Participant participant ;
    @ManyToOne
    @JoinColumn(name="institution_id", referencedColumnName="id")
    private Institution institution ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Conferencier() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setParticipantId( Integer participantId ) {
        this.participantId = participantId ;
    }
    public Integer getParticipantId() {
        return this.participantId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : organisateur ( BIT ) 
    public void setOrganisateur( Boolean organisateur ) {
        this.organisateur = organisateur;
    }
    public Boolean getOrganisateur() {
        return this.organisateur;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    public void setParticipant( Participant participant ) {
        this.participant = participant;
    }
    public Participant getParticipant() {
        return this.participant;
    }


    public void setInstitution( Institution institution ) {
        this.institution = institution;
    }
    public Institution getInstitution() {
        return this.institution;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(participantId);
        sb.append("]:"); 
        sb.append(organisateur);
        return sb.toString(); 
    } 

	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
