/*
 * Created on 28 oct. 2018 ( Time 12:54:50 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.smile.colloque.dao.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "inscription"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="inscription" )
public class Inscription implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
	/*
	 * 
	 */
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="Id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	/*
	 * 
	 */
    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false)
    private Date       date         ;

	/*
	 * 
	 */
    @Column(name="numero_inscription", nullable=false, length=255)
    private String     numeroInscription ;

	/*
	 * 
	 */
    @Column(name="presence")
    private Boolean    presence     ;

	// "participantId" (column "participant_id") is not defined by itself because used as FK in a link 
	// "colloqueId" (column "colloque_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="participant_id", referencedColumnName="id")
    private Participant participant ;
    @ManyToOne
    @JoinColumn(name="colloque_id", referencedColumnName="id")
    private Colloque colloque    ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Inscription() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : date ( DATE ) 
    public void setDate( Date date ) {
        this.date = date;
    }
    public Date getDate() {
        return this.date;
    }

    //--- DATABASE MAPPING : numero_inscription ( VARCHAR ) 
    public void setNumeroInscription( String numeroInscription ) {
        this.numeroInscription = numeroInscription;
    }
    public String getNumeroInscription() {
        return this.numeroInscription;
    }

    //--- DATABASE MAPPING : presence ( BIT ) 
    public void setPresence( Boolean presence ) {
        this.presence = presence;
    }
    public Boolean getPresence() {
        return this.presence;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    public void setParticipant( Participant participant ) {
        this.participant = participant;
    }
    public Participant getParticipant() {
        return this.participant;
    }


    public void setColloque( Colloque colloque ) {
        this.colloque = colloque;
    }
    public Colloque getColloque() {
        return this.colloque;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(date);
        sb.append("|");
        sb.append(numeroInscription);
        sb.append("|");
        sb.append(presence);
        return sb.toString(); 
    } 

	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
