/*
 * Created on 29 oct. 2018 ( Time 11:41:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package ci.smile.colloque.dao.entity;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "organisateur"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="organisateur" )
public class Organisateur implements Serializable, Cloneable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
	/*
	 * 
	 */
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
	/*
	 * 
	 */
    @Column(name="numero_de_telephone", nullable=false, length=255)
    private String     numeroDeTelephone ;

	// "participantId" (column "participant_id") is not defined by itself because used as FK in a link 
	// "colloqueId" (column "colloque_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="participant_id", referencedColumnName="id")
    private Participant participant ;
    @ManyToOne
    @JoinColumn(name="colloque_id", referencedColumnName="id")
    private Colloque colloque    ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Organisateur() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : numero_de_telephone ( VARCHAR ) 
    public void setNumeroDeTelephone( String numeroDeTelephone ) {
        this.numeroDeTelephone = numeroDeTelephone;
    }
    public String getNumeroDeTelephone() {
        return this.numeroDeTelephone;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    public void setParticipant( Participant participant ) {
        this.participant = participant;
    }
    public Participant getParticipant() {
        return this.participant;
    }


    public void setColloque( Colloque colloque ) {
        this.colloque = colloque;
    }
    public Colloque getColloque() {
        return this.colloque;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(numeroDeTelephone);
        return sb.toString(); 
    } 

	//----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
	@Override
	public Object clone() throws CloneNotSupportedException {
		return super.clone();
	}
}
